### ISSUE TITLE
npm 和yarn全部安装失败

### ISSUE THREAD

**Issue by ithack** [3scarecrow/vue-quarter-select#1]
![image](https://user-images.githubusercontent.com/4329193/68655648-5ab9ff80-056b-11ea-8205-e29f28c58386.png)

**Comment by 3scarecrow** [comment]
通过 yarn 安装依赖是可以的，目前通过 npm 安装依赖还有点问题，我会尽快修复的。若yarn安装失败，可贴出图片以供参考

**Comment by ithack** [comment]
> 通过 yarn 安装依赖是可以的，目前通过 npm 安装依赖还有点问题，我会尽快修复的。若yarn安装失败，可贴出图片以供参考

npm 可以安装了，是node版本问题，把node升级到最新版本就可以了

**Comment by ithack** [comment]
> > 通过 yarn 安装依赖是可以的，目前通过 npm 安装依赖还有点问题，我会尽快修复的。若yarn安装失败，可贴出图片以供参考
> 
> npm 可以安装了，是node版本问题，把node升级到最新版本就可以了

execa 这个插件里限制了node版本‘^8.12.0  || >=9.7.0’
