### ISSUE TITLE
可以写一下怎么开发和打包吗

### ISSUE THREAD

**Issue by hansonfang** [3scarecrow/vue-quarter-select#2]

**Comment by 3scarecrow** [comment]
怎么开发是指组件的具体实现过程吗？还是说其他方面的。打包的话是通过Rollup来打包的，打包的配置在 rollup.config.js 文件可以找到，还可以参考Rollup官方文档来了解一些插件的使用。由于该组件是在公司项目中开发的，所以暂时并没有写文章喔。

**Comment by db46rt00ors** [comment]
我也想学一下怎么打包的，我现在自己也维护了一个季度选择器，每次推npm前都要先生成umd版本的插件，然后再手工改下版本，再发布到npm上。好繁琐

**Comment by 3scarecrow** [comment]
其实打包应该都是通过打包工具webpack、rollup或者其他的来处理的

然后对于手动修改版本我是通过一个脚本去控制的

**Comment by 3scarecrow** [comment]
> 我也想学一下怎么打包的，我现在自己也维护了一个季度选择器，每次推npm前都要先生成umd版本的插件，然后再手工改下版本，再发布到npm上。好繁琐

其实打包应该都是通过打包工具webpack、rollup或者其他的来处理的，例如这个季度选择器我是用 rollup 打的，可以参考[rollup.config.js](https://github.com/3scarecrow/vue-quarter-select/blob/master/rollup.config.js)看看

然后对于手动修改版本我是通过一个[发布脚本](https://github.com/3scarecrow/vue-quarter-select/blob/master/scripts/release.js)去控制的，这个脚本的功能：
1. 可以选择发布的版本
2. 是否生成 vuepress 文档
3. 打包成功后自动修改 package.json 的版本（这个应该是你的问题所在）

所以可以参考这个脚本看看
