### ISSUE TITLE
如何只是使用vue-quarter-panel？

### ISSUE THREAD

**Issue by LCQ-x** [3scarecrow/vue-quarter-select#60]
文檔的例子有說怎麼使用和相關參數，但是沒說明怎麼引入，找個很久都沒找到怎麼引入

**Comment by 3scarecrow** [comment]
只引入 vue-quarter-panel 可以使用下面引入，文档上漏了这一点 @LCQ-x 

`import { VueQuarterPanel } from '@3scarecrow/vue-quarter-select'`
