### ISSUE TITLE
季度部分禁用失效，例子属性不可用

### ISSUE THREAD

**Issue by dazafulcoq** [3scarecrow/vue-quarter-select#61]
这是我的上下文
![image](https://github.com/3scarecrow/vue-quarter-select/assets/131439622/ef5c0bf2-9cbf-46d8-b859-342d297081d1)
![image](https://github.com/3scarecrow/vue-quarter-select/assets/131439622/a00d6577-69e5-4bbc-8754-f4d7d2982d50)
使用例子后无法达到禁用效果，且属性失效

**Comment by 3scarecrow** [comment]
> 这是我的上下文 ![image](https://user-images.githubusercontent.com/131439622/259005623-ef5c0bf2-9cbf-46d8-b859-342d297081d1.png) ![image](https://user-images.githubusercontent.com/131439622/259005761-a00d6577-69e5-4bbc-8754-f4d7d2982d50.png) 使用例子后无法达到禁用效果，且属性失效

你应该是用的是 V1 的 VueQuarterSelect，在此版本中要禁用的话，请使用 minDate 和 maxDate Props 实现，V2 才支持 disabledDate Props 的
