### ISSUE TITLE
popper-width配置项不生效

### ISSUE THREAD

**Issue by tzwsm123** [3scarecrow/vue-quarter-select#62]
![222](https://github.com/3scarecrow/vue-quarter-select/assets/56526484/a33ee2c2-0bd0-469c-bb95-89b58ab4771a)

这个地方this.popperWidth || this.triggerWidth + 'px'需要处理成(this.popperWidth || this.triggerWidth) + 'px',否则如果传了popperWidth只会return数字

**Comment by tzwsm123** [comment]
![222](https://github.com/3scarecrow/vue-quarter-select/assets/56526484/9d138407-05dd-4357-9a61-5e6b137f4ce4)

**Comment by 3scarecrow** [comment]
> ![222](https://private-user-images.githubusercontent.com/56526484/299636305-a33ee2c2-0bd0-469c-bb95-89b58ab4771a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMTAwNDksIm5iZiI6MTcwNzIwOTc0OSwicGF0aCI6Ii81NjUyNjQ4NC8yOTk2MzYzMDUtYTMzZWUyYzItMGJkMC00NjljLWJiOTUtODliNThhYjQ3NzFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDA4NTU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyNWM0MTVlNjUzNDIzZDhjODEzMzAyOTJlMTBiYTRhYmRkMjdiNGExMTljZjQxOThjMTJjYzAzYmNhYzUxZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zZ7Yw7aouPDw7BFuSvAAGLtne8TzrqnUxCMiSez4ftg)
> 
> 这个地方this.popperWidth || this.triggerWidth + 'px'需要处理成(this.popperWidth || this.triggerWidth) + 'px',否则如果传了popperWidth只会return数字

感谢反馈 ，已在 2.0.1 版本已修复
